In [0]:
import numpy as np
import tensorflow as tf

In [45]:
d4array = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],[19,20,21,22,23,24,25,26,27,28,29,30,31,31,33,34,35,36]])

print(d4array.shape)

resizedArray = np.reshape(d4array, (d4array.shape[0],3,2,3))

print(resizedArray.shape)

print(resizedArray[0])

print("####")
#print(resizedArray[1])

print("@@@@")

#print(np.mean(resizedArray,1))

#print(np.mean(resizedArray,1).shape)

print(resizedArray[:,0,:,:])

#print(resizedArray[:,:,0,:])

print("!!!!!")


print(resizedArray[:,1,:,:])

#print(resizedArray[:,:,1,:])

print("!!!!!")

print(resizedArray[:,2,:,:])
      
print("!!!!!")

sum = np.sum(resizedArray,1)

print(sum)

nelem = resizedArray.shape[1]

print(nelem)


mean1 = sum / ((float)(nelem))

print("%%%%%")

print(mean1)

print("%%%%%")
print(np.mean(resizedArray,1))

print("Before reshape")

arr2 = np.mean(resizedArray,1).reshape(2,-1)

print(arr2)

sess = tf.InteractiveSession()

print(tf.reduce_sum(resizedArray,1).eval())

sess.close()

(2, 18)
(2, 3, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
####
@@@@
[[[ 1  2  3]
  [ 4  5  6]]

 [[19 20 21]
  [22 23 24]]]
!!!!!
[[[ 7  8  9]
  [10 11 12]]

 [[25 26 27]
  [28 29 30]]]
!!!!!
[[[13 14 15]
  [16 17 18]]

 [[31 31 33]
  [34 35 36]]]
!!!!!
[[[21 24 27]
  [30 33 36]]

 [[75 77 81]
  [84 87 90]]]
3
%%%%%
[[[ 7.          8.          9.        ]
  [10.         11.         12.        ]]

 [[25.         25.66666667 27.        ]
  [28.         29.         30.        ]]]
%%%%%
[[[ 7.          8.          9.        ]
  [10.         11.         12.        ]]

 [[25.         25.66666667 27.        ]
  [28.         29.         30.        ]]]
Before reshape
[[ 7.          8.          9.         10.         11.         12.        ]
 [25.         25.66666667 27.         28.         29.         30.        ]]
[[[21 24 27]
  [30 33 36]]

 [[75 77 81]
  [84 87 90]]]


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
